
#siliconflow
SILICONFLOW:
  BASE_URL: "https://api.siliconflow.cn/v1"
  API_KEY: "sk-glivxumizpjdkbgxbdnwaeuecmkzugydhpwnefbkfcvdqwge"
  DeepSeek-R1-Distill-Qwen-7B: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
  Qwen3-8B: "Qwen/Qwen3-8B"

